require 'spec_helper'
require 'get_counted_nucleotides'

describe 'get_counted_nucleotides' do
  it 'some examples' do
    expect(get_counted_nucleotides('TTT')).to eq({"A" => 0, "C" => 0, "G" => 0, "T" => 3})
    expect(get_counted_nucleotides('ACGT')).to eq({"A" => 1, "C" => 1, "G" => 1, "T" => 1})
    expect(get_counted_nucleotides('AAACGT')).to eq({"A" => 3, "C" => 1, "G" => 1, "T" => 1})
    expect(get_counted_nucleotides('')).to eq({"A" => 0, "C" => 0, "G" => 0, "T" => 0})
    expect(get_counted_nucleotides('GTGTCGGCCGTAAGCCGAATTTGTGCCTATGGCCTAGTTTAGTAACGTATCGGGCGTTTGTACACCACTAGCAGGACAACACGGAATAGCATCGCATGTTTAAAGTCACTGGAGGAGGGAGGCGACCTCATCTTGGACGTTTGCTACACACTCTACCCCGGTGTTTGAGTATCGGGGCGGTTCTGGCCGAGAGGGGTAGTTTATAATCTTCGTGGTCCCTATGTAGGCAGCGTAGTGATGCAACACGCCTCGAGTTAGTTGGGAGGTACGAGCTCTGGGTAAGAGGCAGGACCAATTACTACTGAGAAGTCACTAGACTGGCAACGTCCGTTATACTTCATGTAGACTGGGCTCTTTTGTCAACTCGGCAGGCACGCCTCCCGAGCATATGGAAAACCGGCAGGAACTCCAAGTTGTTTGGTCCCACGGGTCAACAAATCTTCAAGACTAGTGTGGAAGTCCCTGATGGCGCCGCCAAGTTGCGGACACTCAGACCTATTGAATCTAGCCATCCTTAGTAAGCGTACTGTCATACTTGTCTAGGTGCGGAGGATCGCGATTTAGGGCAAGCCTCAGATGGTTTGCTCTGCCTTAATGTTAGGGAGGTAAAATATGCGCATTGAATTTGGGATTAGCTGAGTAGAGCCTACCCAGGTTCGTTGCAGAACGAGTCAACACAAGCTCTCGCCCTTTTTGTTCCGACCGAGACAGCCTTCCCAATAAGGCACGCAACGCCACGTGTCATCGACATTAGCAAGCGACCGATGTGATATAGTAGAGTATCGGGGCAATCAGTGTTAACACTAGGATCAGCTTGTCTACGATCGCCGGGCAAGGGCTGTACAGACGTTATATGCTGGTTCGTCCACGGGGTTTACCACGTCCGGAGTCAACGTAGCGCAATGGGGAACTTACCGGATTGAGCGTAATCTCACATGGCGCAGAAAAGAATGTGGTTGGACGAAGTCCATAACTGAAGGTTAGCGA')).to eq({"A"=>243, "C"=>228, "G"=>276, "T"=>240})
  end
end

